### ISSUE TITLE
Error on (paper) MC 1.14.4

### ISSUE THREAD

**Issue by thiefa** [janka102/Bullseye#3] opened 2019-08-24 10:02 UTC
Hi, 
my Bullseye wont work anymore on MC1.14.4 (Paper) 
it dosent create any errors during server startup, but on creating a sign the console gives out:

`[13:41:43 ERROR]: Could not pass event SignChangeEvent to Bullseye v0.8.1
java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign
        at com.github.janka102.bullseye.SignListener.onSignChange(Unknown Source) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor20.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-159]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2567) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-159]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]`

upon hitting existing signs, the console prints out:

`[13:48:24 ERROR]: Could not pass event ProjectileHitEvent to Bullseye v0.8.1
java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign
        at com.github.janka102.bullseye.SignUtils.getBullseyeSigns(Unknown Source) ~[?:?]
        at com.github.janka102.bullseye.ArrowListener.onArrowHit(Unknown Source) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor33.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-159]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-159]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1231) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.EntityArrow.a(EntityArrow.java:284) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.EntityArrow.tick(EntityArrow.java:199) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.EntityTippedArrow.tick(EntityTippedArrow.java:87) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:584) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.World.a(World.java:936) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:356) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-159]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-159]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]`

i testet it on a blank server, to be sure it is not any kind of plugin interference.

is there a chance you can fix it to run under MC1.14.4?

**Comment by janka102** [comment] 2019-08-25 02:57
Hello,

The current Minecraft version compatible with Bullseye is 1.12.

There were changes done in 1.13/1.14 that break Bullseye even if I try to build it with those versions specifically. I don't have much time right now to update it unfortunately, but it is on my long to-do list of things.

**Comment by janka102** [comment] 2022-04-09 21:48
I released a version a few months ago that works with Minecraft 1.13-1.17, you can go ahead and give it a shot now!
https://dev.bukkit.org/projects/bullseye/files

**Comment by janka102** [comment] 2022-08-03 23:26
I have looked into this issue and it seems from all the versions currently supported (1.13-1.19) only version 1.14 has the odd errors in the console. I was not able to find out the root cause when looking into this. It also doesn't seem to affect the functionality of the plugin or the game. Since it's only logging those on 1.14 I will close this as a won't fix.

**Closed as completed by janka102** 2022-08-03 23:26 UTC
Labels: wontfix
